#!/usr/bin/env ruby
# frozen_string_literal: true

ENV['RACK_ENV'] ||= 'development'

require "bundler/setup"
require "convos"

# You can add fixtures and/or initialization code here to make experimenting
# with your gem easier. You can also use a different console, if you like.

require "irb"
IRB.start(__FILE__)
